
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox5;

	private global::Gtk.VBox vbox8;

	private global::Gtk.Label Titulo;

	private global::Gtk.Entry entry1;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button BReset;

	private global::Gtk.Button BBorrar;

	private global::Gtk.HBox hbox3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button B7;

	private global::Gtk.Button B8;

	private global::Gtk.Button B9;

	private global::Gtk.Button BDividir;

	private global::Gtk.HBox hbox5;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button B4;

	private global::Gtk.Button B5;

	private global::Gtk.Button B6;

	private global::Gtk.Button BMultiplicar;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox7;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Button B1;

	private global::Gtk.Button B2;

	private global::Gtk.Button B3;

	private global::Gtk.Button BRestar;

	private global::Gtk.HBox hbox9;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Button BComa;

	private global::Gtk.Button B;

	private global::Gtk.Button BIgual;

	private global::Gtk.Button BSumar;

	private global::Gtk.Button Bcient;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		this.vbox5.BorderWidth = ((uint)(15));
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.Titulo = new global::Gtk.Label();
		this.Titulo.HeightRequest = 30;
		this.Titulo.Name = "Titulo";
		this.Titulo.LabelProp = global::Mono.Unix.Catalog.GetString("Calculadora");
		this.vbox8.Add(this.Titulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.Titulo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.WidthRequest = 290;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = false;
		this.entry1.InvisibleChar = '•';
		this.vbox8.Add(this.entry1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.entry1]));
		w2.Position = 1;
		this.vbox5.Add(this.vbox8);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox8]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BReset = new global::Gtk.Button();
		this.BReset.WidthRequest = 223;
		this.BReset.CanFocus = true;
		this.BReset.Name = "BReset";
		this.BReset.UseUnderline = true;
		this.BReset.Label = global::Mono.Unix.Catalog.GetString("Reset");
		this.hbox2.Add(this.BReset);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.BReset]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BBorrar = new global::Gtk.Button();
		this.BBorrar.WidthRequest = 70;
		this.BBorrar.CanFocus = true;
		this.BBorrar.Name = "BBorrar";
		this.BBorrar.UseUnderline = true;
		this.BBorrar.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox2.Add(this.BBorrar);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.BBorrar]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox6.Add(this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.B7 = new global::Gtk.Button();
		this.B7.WidthRequest = 70;
		this.B7.CanFocus = true;
		this.B7.Name = "B7";
		this.B7.UseUnderline = true;
		this.B7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox4.Add(this.B7);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.B7]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.B8 = new global::Gtk.Button();
		this.B8.WidthRequest = 70;
		this.B8.CanFocus = true;
		this.B8.Name = "B8";
		this.B8.UseUnderline = true;
		this.B8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox4.Add(this.B8);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.B8]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.B9 = new global::Gtk.Button();
		this.B9.WidthRequest = 70;
		this.B9.CanFocus = true;
		this.B9.Name = "B9";
		this.B9.UseUnderline = true;
		this.B9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox4.Add(this.B9);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.B9]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.BDividir = new global::Gtk.Button();
		this.BDividir.WidthRequest = 70;
		this.BDividir.CanFocus = true;
		this.BDividir.Name = "BDividir";
		this.BDividir.UseUnderline = true;
		this.BDividir.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox3.Add(this.BDividir);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.BDividir]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox6.Add(this.hbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox3]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.B4 = new global::Gtk.Button();
		this.B4.WidthRequest = 70;
		this.B4.CanFocus = true;
		this.B4.Name = "B4";
		this.B4.UseUnderline = true;
		this.B4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox6.Add(this.B4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.B4]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.B5 = new global::Gtk.Button();
		this.B5.WidthRequest = 70;
		this.B5.CanFocus = true;
		this.B5.Name = "B5";
		this.B5.UseUnderline = true;
		this.B5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox6.Add(this.B5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.B5]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.B6 = new global::Gtk.Button();
		this.B6.WidthRequest = 70;
		this.B6.CanFocus = true;
		this.B6.Name = "B6";
		this.B6.UseUnderline = true;
		this.B6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox6.Add(this.B6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.B6]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox5.Add(this.hbox6);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox6]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.BMultiplicar = new global::Gtk.Button();
		this.BMultiplicar.WidthRequest = 70;
		this.BMultiplicar.CanFocus = true;
		this.BMultiplicar.Name = "BMultiplicar";
		this.BMultiplicar.UseUnderline = true;
		this.BMultiplicar.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox5.Add(this.BMultiplicar);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.BMultiplicar]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox6.Add(this.hbox5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox5.Add(this.vbox6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.B1 = new global::Gtk.Button();
		this.B1.WidthRequest = 70;
		this.B1.CanFocus = true;
		this.B1.Name = "B1";
		this.B1.UseUnderline = true;
		this.B1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox8.Add(this.B1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.B1]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.B2 = new global::Gtk.Button();
		this.B2.WidthRequest = 70;
		this.B2.CanFocus = true;
		this.B2.Name = "B2";
		this.B2.UseUnderline = true;
		this.B2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox8.Add(this.B2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.B2]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.B3 = new global::Gtk.Button();
		this.B3.WidthRequest = 70;
		this.B3.CanFocus = true;
		this.B3.Name = "B3";
		this.B3.UseUnderline = true;
		this.B3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox8.Add(this.B3);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.B3]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox7.Add(this.hbox8);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox8]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.BRestar = new global::Gtk.Button();
		this.BRestar.WidthRequest = 70;
		this.BRestar.CanFocus = true;
		this.BRestar.Name = "BRestar";
		this.BRestar.UseUnderline = true;
		this.BRestar.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox7.Add(this.BRestar);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.BRestar]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox7.Add(this.hbox7);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.BComa = new global::Gtk.Button();
		this.BComa.WidthRequest = 70;
		this.BComa.CanFocus = true;
		this.BComa.Name = "BComa";
		this.BComa.UseUnderline = true;
		this.BComa.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox10.Add(this.BComa);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.BComa]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.B = new global::Gtk.Button();
		this.B.WidthRequest = 70;
		this.B.CanFocus = true;
		this.B.Name = "B";
		this.B.UseUnderline = true;
		this.B.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox10.Add(this.B);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.B]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.BIgual = new global::Gtk.Button();
		this.BIgual.WidthRequest = 70;
		this.BIgual.CanFocus = true;
		this.BIgual.Name = "BIgual";
		this.BIgual.UseUnderline = true;
		this.BIgual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox10.Add(this.BIgual);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.BIgual]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.hbox9.Add(this.hbox10);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox10]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.BSumar = new global::Gtk.Button();
		this.BSumar.WidthRequest = 70;
		this.BSumar.CanFocus = true;
		this.BSumar.Name = "BSumar";
		this.BSumar.UseUnderline = true;
		this.BSumar.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox9.Add(this.BSumar);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.BSumar]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox7.Add(this.hbox9);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox9]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		this.vbox5.Add(this.vbox7);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox7]));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.Bcient = new global::Gtk.Button();
		this.Bcient.CanFocus = true;
		this.Bcient.Name = "Bcient";
		this.Bcient.UseUnderline = true;
		this.Bcient.Label = global::Mono.Unix.Catalog.GetString("Calculadora científica");
		this.vbox5.Add(this.Bcient);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.Bcient]));
		w33.Position = 3;
		w33.Expand = false;
		w33.Fill = false;
		this.Add(this.vbox5);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 329;
		this.DefaultHeight = 355;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BReset.Clicked += new global::System.EventHandler(this.OnClickReset);
		this.BBorrar.Clicked += new global::System.EventHandler(this.OnClickBorrar);
		this.B7.Clicked += new global::System.EventHandler(this.OnClick7);
		this.B8.Clicked += new global::System.EventHandler(this.OnClick8);
		this.B9.Clicked += new global::System.EventHandler(this.OnClick9);
		this.BDividir.Clicked += new global::System.EventHandler(this.OnClickDividir);
		this.B4.Clicked += new global::System.EventHandler(this.OnClick4);
		this.B5.Clicked += new global::System.EventHandler(this.OnClick5);
		this.B6.Clicked += new global::System.EventHandler(this.OnClick6);
		this.BMultiplicar.Clicked += new global::System.EventHandler(this.OnClickMult);
		this.B1.Clicked += new global::System.EventHandler(this.OnClick1);
		this.B2.Clicked += new global::System.EventHandler(this.OnClick2);
		this.B3.Clicked += new global::System.EventHandler(this.OnClick3);
		this.BRestar.Clicked += new global::System.EventHandler(this.OnClickRest);
		this.BComa.Clicked += new global::System.EventHandler(this.OnClickComa);
		this.B.Clicked += new global::System.EventHandler(this.OnClick0);
		this.BIgual.Clicked += new global::System.EventHandler(this.OnClickIgual);
		this.BSumar.Clicked += new global::System.EventHandler(this.OnClickSuma);
		this.Bcient.Clicked += new global::System.EventHandler(this.OnClickCient);
	}
}
