
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label Titulo;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry entrada;

	private global::Gtk.Button button1;

	private global::Gtk.Label Aleatorio1;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label minLabel;

	private global::Gtk.Entry min;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label maxLabel;

	private global::Gtk.Entry max;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button Aleatorio;

	private global::Gtk.HBox hbox6;

	private global::Gtk.HBox hbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button BSalir;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Titulo = new global::Gtk.Label();
		this.Titulo.HeightRequest = 37;
		this.Titulo.Name = "Titulo";
		this.Titulo.LabelProp = global::Mono.Unix.Catalog.GetString("Titulo");
		this.vbox1.Add(this.Titulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Titulo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entrada = new global::Gtk.Entry();
		this.entrada.CanFocus = true;
		this.entrada.Name = "entrada";
		this.entrada.IsEditable = true;
		this.entrada.InvisibleChar = '•';
		this.hbox1.Add(this.entrada);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entrada]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Dime tu nombre");
		this.hbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Aleatorio1 = new global::Gtk.Label();
		this.Aleatorio1.HeightRequest = 40;
		this.Aleatorio1.Name = "Aleatorio1";
		this.Aleatorio1.LabelProp = global::Mono.Unix.Catalog.GetString("Aleatorio");
		this.vbox1.Add(this.Aleatorio1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Aleatorio1]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.minLabel = new global::Gtk.Label();
		this.minLabel.Name = "minLabel";
		this.minLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Mínimo");
		this.hbox4.Add(this.minLabel);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.minLabel]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.min = new global::Gtk.Entry();
		this.min.CanFocus = true;
		this.min.Name = "min";
		this.min.IsEditable = true;
		this.min.InvisibleChar = '•';
		this.hbox4.Add(this.min);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.min]));
		w7.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.maxLabel = new global::Gtk.Label();
		this.maxLabel.Name = "maxLabel";
		this.maxLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Máximo");
		this.hbox5.Add(this.maxLabel);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.maxLabel]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.max = new global::Gtk.Entry();
		this.max.CanFocus = true;
		this.max.Name = "max";
		this.max.IsEditable = true;
		this.max.InvisibleChar = '•';
		this.hbox5.Add(this.max);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.max]));
		w9.Position = 1;
		this.hbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
		w10.Position = 2;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.Aleatorio = new global::Gtk.Button();
		this.Aleatorio.CanFocus = true;
		this.Aleatorio.Name = "Aleatorio";
		this.Aleatorio.UseUnderline = true;
		this.Aleatorio.Label = global::Mono.Unix.Catalog.GetString("Aleatorio");
		this.hbox7.Add(this.Aleatorio);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Aleatorio]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add(this.hbox7);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
		w13.Position = 4;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		this.vbox1.Add(this.hbox6);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
		w14.Position = 5;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.BSalir = new global::Gtk.Button();
		this.BSalir.CanFocus = true;
		this.BSalir.Name = "BSalir";
		this.BSalir.UseUnderline = true;
		this.BSalir.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.hbox3.Add(this.BSalir);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.BSalir]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
		w16.Position = 2;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w17.Position = 6;
		w17.Expand = false;
		w17.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 451;
		this.DefaultHeight = 337;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.OnBSaludar);
		this.Aleatorio.Clicked += new global::System.EventHandler(this.OnBAleatorio);
		this.BSalir.Clicked += new global::System.EventHandler(this.OnBSalir);
	}
}
