
// This file has been generated by the GUI designer. Do not modify.
namespace Bingo
{
	public partial class Carton
	{
		private global::Gtk.VBox vbcarton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Bingo.Carton
			this.Name = "Bingo.Carton";
			this.Title = global::Mono.Unix.Catalog.GetString("Carton");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(9));
			// Container child Bingo.Carton.Gtk.Container+ContainerChild
			this.vbcarton = new global::Gtk.VBox();
			this.vbcarton.Name = "vbcarton";
			this.vbcarton.Spacing = 6;
			this.Add(this.vbcarton);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 262;
			this.DefaultHeight = 164;
			this.Show();
		}
	}
}
