
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label titulo;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button BLanzar;

	private global::Gtk.Button BReset;

	private global::Gtk.Button BSalir;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Button NBoleto;

	private global::Gtk.VBox vbox4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.titulo = new global::Gtk.Label();
		this.titulo.HeightRequest = 30;
		this.titulo.Name = "titulo";
		this.titulo.LabelProp = global::Mono.Unix.Catalog.GetString("El Bingo");
		this.vbox2.Add(this.titulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.titulo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BLanzar = new global::Gtk.Button();
		this.BLanzar.WidthRequest = 120;
		this.BLanzar.CanFocus = true;
		this.BLanzar.Name = "BLanzar";
		this.BLanzar.UseUnderline = true;
		this.BLanzar.Label = global::Mono.Unix.Catalog.GetString("Lanzar");
		this.hbox1.Add(this.BLanzar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BLanzar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BReset = new global::Gtk.Button();
		this.BReset.WidthRequest = 120;
		this.BReset.CanFocus = true;
		this.BReset.Name = "BReset";
		this.BReset.UseUnderline = true;
		this.BReset.Label = global::Mono.Unix.Catalog.GetString("Reset");
		this.hbox1.Add(this.BReset);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BReset]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BSalir = new global::Gtk.Button();
		this.BSalir.WidthRequest = 120;
		this.BSalir.CanFocus = true;
		this.BSalir.Name = "BSalir";
		this.BSalir.UseUnderline = true;
		this.BSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.hbox1.Add(this.BSalir);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BSalir]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w6.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.NBoleto = new global::Gtk.Button();
		this.NBoleto.CanFocus = true;
		this.NBoleto.Name = "NBoleto";
		this.NBoleto.UseUnderline = true;
		this.NBoleto.Label = global::Mono.Unix.Catalog.GetString("NuevoBoleto");
		this.vbox3.Add(this.NBoleto);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.NBoleto]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w8.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.vbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
		w9.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BLanzar.Clicked += new global::System.EventHandler(this.OnClickLanzar);
		this.BReset.Clicked += new global::System.EventHandler(this.OnClickReset);
		this.BSalir.Clicked += new global::System.EventHandler(this.OnClickSalir);
		this.NBoleto.Clicked += new global::System.EventHandler(this.OnClickNBoleto);
	}
}
